### ISSUE TITLE
Schema level title and description twice on the generated starter form

### ISSUE THREAD

**Issue by datakurre** [deathbeds/jupyterlab-starters#30]
When, e.g. on jupyterlab-starters binder, I update "Multi-Stage Starter Notebook"'s schema to include title and description:

```
    "schema": {
     "title": "Schema title",
     "description": "Schema description",
     "properties": {
      "name": {
       "description": "What is your name?",
       "title": "Name",
       "type": "string"
      }
     },
```

The form opened from the launcher will show title and description twice:

```
Schema title

Schema description

Schema title

Schema description

Name*

What is your name?

    is a required property
```

**Comment by bollwyvl** [comment]
eek!

**Comment by datakurre** [comment]
Also the layout is pretty tight:

![jupyterlab-starters](https://user-images.githubusercontent.com/160447/71645125-0d8d1b00-2cdc-11ea-8fa6-f52a7d84bc33.png)

for

```
    "schema": {                                                                         
     "title": "# Welcome to Robot Framework on Jupyter",                                
     "description": "Please, click **START** to launch the tutorial.",                  
     "properties": {},                                                                  
     "required": []                                                                     
    },  
```

**Comment by bollwyvl** [comment]
Ah. The formatting issue aside, it appears that adding `type` clears up the duplicate `title` and `description`:
```yaml
    "schema": {
     "type": "object",  # <--- this right here
     "title": "# Welcome to Robot Framework on Jupyter",                                
     "description": "Please, click **START** to launch the tutorial.",                  
     "properties": {},                                                                  
     "required": []                                                                     
    },  
```

Could actually demand that the root-level schema be an object...
