### ISSUE TITLE
Expand templates in destination, commands

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jupyterlab-starters#9]
## Elevator Pitch
Currently, only the `dest` field has Jinja templates enabled, and can only see the `body` of text. Expanding what is available for templating, and what is templated, would allow JSON-only definitions to have more expressive power

## Motivation

Over on robotlab, we want to do a simple copy of a folder, and then open a particular, known notebook.

## Design Ideas

```yaml
StarterManager:
  extra_starters:
    robotkernel-examples:
      src: {{ sys_prefix }}/var/www/robotkernel-examples
      commands:
        - id: filebrowser:open-path
          args:
            path: {{ dest }}/00 JupyterLab Interface.ipynb
```
The simplest approach may be to dump to JSON, apply Jinja, and then reload
